// Copyright (c) 2024 FoxCouncil - https://github.com/FoxCouncil/NAPLPS

using NAPLPS;

#if NET8_0_WINDOWS
using NAPLPSApp.Forms;
#endif

namespace NAPLPSApp;

internal static class Program
{
    /// <summary>NAPLPS App - A toolbox and GUI system for modern NAPLPS rendering and creation</summary>
    [STAThread]
    static void Main(FileInfo input)
    {
        if (input != null)
        {
            ProccessInput(input);

            return;
        }

#if NET8_0_WINDOWS
        Console.WriteLine("Starting GUI...");

        ApplicationConfiguration.Initialize();

        var thread = new Thread(() => Application.Run(new MainNaplpsForm()));

        thread.SetApartmentState(ApartmentState.STA);
        thread.Start();
        thread.Join();
#else
        // No GUI so we show the default generated help.
        System.CommandLine.DragonFruit.CommandLine.ExecuteAssembly(typeof(AutoGeneratedProgram).Assembly, new string[] { "--help" }, "");
#endif
    }

    private static void ProccessInput(FileInfo input)
    {
        if (!input.Exists)
        {
            Console.WriteLine("NaplpsApp: Error, [input] file does not exist, check your path and try again.");

            return;
        }

        var naplpsFile = NaplpsFormat.FromFile(input.FullName);

        if (!naplpsFile.IsValid)
        {
            Console.WriteLine("NaplpsApp: Error, [input] file does not seem to be a valid NAPLPS formatted file");

            return;
        }

        var filename = input.Name;

        if (!FileFunctions.Convert(naplpsFile, filename))
        {
            Console.WriteLine("NaplpsApp: Error, [input] failed to convert.");

            return;
        }

        Console.WriteLine("NaplpsApp: [input] converted successfully.");
    }
}